# Generated by Django 3.2.4 on 2023-01-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('status', models.CharField(default='published', max_length=10, verbose_name='Status')),
                ('product_name', models.CharField(default='Título do produto desconhecido', max_length=250, verbose_name='Nome do produto')),
                ('quantity', models.CharField(blank=True, default='Sem informações sobre quantidades', max_length=200, verbose_name='Quantidade')),
                ('brands', models.CharField(blank=True, default='Sem informações sobre Marcas', max_length=100, verbose_name='Marcas')),
                ('categories', models.CharField(blank=True, default='Sem informações sobre Categorias', max_length=255, verbose_name='Categorias')),
                ('labels', models.CharField(blank=True, default='Sem informações sobre Labels', max_length=255, verbose_name='Labels')),
                ('cities', models.CharField(blank=True, default='Sem informações sobre cidades', max_length=255, verbose_name='Cidades')),
                ('purchase_places', models.CharField(blank=True, default='Sem informações sobre Locais de compra', max_length=255, verbose_name='Locais de compra')),
                ('stores', models.CharField(blank=True, default='Sem informações sobre lojas', max_length=255, verbose_name='Lojas')),
                ('ingredients_text', models.TextField(blank=True, default='Sem informações sobre ingredientes')),
                ('url', models.CharField(blank=True, default='Não há uma URL registrada', max_length=255, verbose_name='Url')),
                ('creator', models.CharField(blank=True, default='Não informado', max_length=20, verbose_name='Criador')),
                ('traces', models.CharField(blank=True, default='Sem informações sobre Traces', max_length=255, verbose_name='Traces')),
                ('serving_size', models.CharField(blank=True, default='Sem informações sobre Porções', max_length=50, verbose_name='Porçoes')),
                ('serving_quantity', models.CharField(blank=True, default=None, max_length=50, verbose_name='Quantidade servida')),
                ('nutriscore_score', models.CharField(blank=True, default=0, max_length=50, verbose_name='Nutriscore')),
                ('nutriscore_grade', models.CharField(blank=True, max_length=5, null=True, verbose_name='Nota Nutriscore')),
                ('main_category', models.CharField(blank=True, default='Sem informações sobre Categoria principal', max_length=100, verbose_name='Categoria principal')),
                ('image_url', models.CharField(blank=True, default='Sem URL de imagem do Produto', max_length=255, verbose_name='Url da imagem')),
                ('imported_t', models.DateTimeField(auto_now=True, verbose_name='Data e hora da importação')),
                ('created_t', models.DateField(blank=True, null=True, verbose_name='Data da criação')),
                ('last_modified_t', models.DateField(blank=True, null=True, verbose_name='Data da última modificação')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
