# Generated by Django 3.2.4 on 2023-01-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCrons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('sucesso', models.BooleanField(default=True)),
                ('data', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro CRON',
                'verbose_name_plural': 'Registros CRON',
            },
        ),
    ]
